### PR TITLE
Added titles to pages

### PR DESCRIPTION
**Pull request by dorkrawk**
Hey, I couldn't sleep tonight so I decided to try to add titles to a bunch of the pages on your March Sadness site.

I haven't really done much with Node or Jade and I couldn't get the site up and running locally to really test this patch, but I think it's pretty close.

### CODE REVIEW

**Comment by MSherry24** [comment]
You are amazing.
It looks good at a glance.  I'll test it out tonight and let you know how it goes.

**Comment by dorkrawk** [comment]
No problem, I'm always interested in the stuff friends post on Github and I now have a vested interest with my "Why Is My Coffee Shaking!?" ballot.

So how do I get the site up and running locally? I tried doing (from the project directory):

```
> node install
> grunt
```

But I ran into a bunch of errors.  Also do you need to separately install Mongo?

**Comment by MSherry24** [comment]
Yeah, you'll need mongo running locally.  It should be enough to start it up and point it at an empty data directory.  npm install is necessary, but you got that covered.  I don't actually have any grunt tasks set up, so you can ignore that step.

Once you have mongo running, go to the top directory (the one with app.js) and type npm start.  That should be it.

**Comment by dorkrawk** [comment]
Ok, I got the site running locally and was able to actually test this patch, so I had to fix a few things. It should work now. Obviously change the titles to whatever you think would be best.

**Comment by MSherry24** [comment]
Looks good!  I'm pretty pleased with your title choices.  Thanks, again.  I hope you enjoyed your node experience.

**Pull request merged**
